name: core
description: Shared domain & data logic
version: 0.0.1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter


  json_annotation: ^4.9.0
  dio: ^5.3.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.4
  provider: ^6.0.5

dev_dependencies:
  build_runner: ^2.7.0
  json_serializable: ^6.11.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

